In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## GET DATA READY

In [3]:
bug = pd.read_csv('../Data(Sound & Text)/Text/bug-pit.txt')

In [5]:
bug.head()

text
0  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...
1  هل اصابك شيء فيها مثل رفعت عشره او ضربه عصا او...
2  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...
3  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...
4  هل اصابك شيء فيها مثل لاذعه حشره او ضرب في عصا...

In [6]:
bug['class'] = 'bug-pit'

In [7]:
bug.head(10)

text    class
0  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...  bug-pit
1  هل اصابك شيء فيها مثل رفعت عشره او ضربه عصا او...  bug-pit
2  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...  bug-pit
3  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...  bug-pit
4  هل اصابك شيء فيها مثل لاذعه حشره او ضرب في عصا...  bug-pit
5  هل اصابك شيء فيها مثل رفعت حشره او ضرب او نحو ذلك  bug-pit
6  هل اصابك شيء فيها مثل والزعتر تحشر او ضربه عصا...  bug-pit
7  هل اصابك شيء فيها مثل اذا تحشر او ضربت عسى او ...  bug-pit
8  هل اصابك شيء فيها مثل الافعى حشره او ضربه عصا ...  bug-pit
9  هل اصابك شيء فيها مثل لسعات حشره او ضربه عصا ا...  bug-pit

In [8]:
direction = pd.read_csv('../Data(Sound & Text)/Text/direction.txt')
direction['class'] = 'direction'
direction.tail(6)

text      class
49       الى اين تتجه هذه العلامه وهذه وهذه  direction
50       الى اين تتجه هذه العلامه وهذه وهذه  direction
51  الى اين تتجه هذه العلامه وهذه وهذه وهذه  direction
52  الى اين تتجه هذه العلامه وهذه وهذه وهذه  direction
53  الى اين تتجه هذه العلامه وهذه وهذه وهذه  direction
54  الى اين تتجه هذه العلامه وهذه وهذه وهذه  direction

In [10]:
Sugar = pd.read_csv('../Data(Sound & Text)/Text/Sugar.txt')
Sugar['class'] = 'Sugar'
Sugar.tail(6)

text  class
46        هل لديك مرض السكري او اي مرض مزمن  Sugar
47             هل لديك مرض السكري او اي مرض  Sugar
48  هل لديك مرض السكري او اي او اي مرض مزمن  Sugar
49        هل لديك مرض السكري او اي مرض مزمن  Sugar
50        هل لديك مرض السكري او اي مرض مزمن  Sugar
51             هل لديك مرض السكري او اي مرض  Sugar

In [11]:
glasses = pd.read_csv('../Data(Sound & Text)/Text/glasses.txt')
glasses['class'] = 'glasses'
glasses.tail(6)

text    class
46  وهذه هذه النظاره ارسلها  glasses
47        ارتدي هذه النظاره  glasses
48        يرتدي هذه النظاره  glasses
49        ارتدي هذه النظاره  glasses
50        ابتدي هذه النظاره  glasses
51        ارتدي هذه النظاره  glasses

In [12]:
headache = pd.read_csv('../Data(Sound & Text)/Text/headache.txt')
headache['class'] = 'headache'
headache.tail(16)

text     class
37                     تجعر بالصداع  headache
38                    هل تشعر بصداع  headache
39                     اشعر بالصداع  headache
40    هل تجعر وصداع هل تجعلوا بصداع  headache
41    السؤال الثالث هل تشعر بالصداع  headache
42                    هل تشعر بصداع  headache
43                   هل تجرب الصداع  headache
44                  هل تشعر بالصداع  headache
45                  هل تشعر بالصداع  headache
46  هل تشعر بالصداع هل تشعر بالصداع  headache
47                    هل تشعر بصداع  headache
48                          هل تشعر  headache
49                    هل تشعر بصداع  headache
50                    هل تشعر بصداع  headache
51                    هل تشرب لصداع  headache
52                    هل تشعر بصداع  headache

In [13]:
ray = pd.read_csv('../Data(Sound & Text)/Text/ray.txt')
ray['class'] = 'ray'
ray.head(8)

text class
0         اسامي الاشعه بعمل صوره اشعه للعينين   ray
1    اذهب الى الاشعه و اعمل صوره اشعه للعينين   ray
2    اذهب الى الاشعه و اعمل صوره اشعه للعينين   ray
3   اذهب الى الاشعه و اعمل صوره اشعه من العين   ray
4                الاشعه وين صوره اشعه للعينين   ray
5     اذهب الى الاشعه واعمر صوره اشعه للعينين   ray
6  اذهب الى الاشعه وقم بعمل صوره اسال العينين   ray
7    اذهب الى الاشعه و اعمل صوره اشعه للعينين   ray

In [14]:
Sit_down = pd.read_csv('../Data(Sound & Text)/Text/Sit-down.txt')
Sit_down['class'] = 'Sit-down'
Sit_down.head(10)

text     class
0   حسنا اللي في نامي فضلك وضع راسك في هذا الجهاز  Sit-down
1    حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز  Sit-down
2    حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز  Sit-down
3    حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز  Sit-down
4    حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز  Sit-down
5    حسنا اجلس هنا من فضلك قطع راسك في هذا الجهاز  Sit-down
6  حسنا اجلس هنا من فضلك وضاع راسخه في هذا الجهاز  Sit-down
7  حسنا اجلس هنا من فضلك وضاع راسخه في هذا الجهاز  Sit-down
8       اجلس هنا من فضلك وضع الماسك في هذا الجهاز  Sit-down
9    حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز  Sit-down

## Make a Data set from our data

In [15]:
pdList = [bug, direction, Sugar, glasses, headache, ray, Sit_down]  # List of your dataframes

In [16]:
df = pd.concat(pdList)

In [17]:
df.head(10)

text    class
0  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...  bug-pit
1  هل اصابك شيء فيها مثل رفعت عشره او ضربه عصا او...  bug-pit
2  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...  bug-pit
3  هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...  bug-pit
4  هل اصابك شيء فيها مثل لاذعه حشره او ضرب في عصا...  bug-pit
5  هل اصابك شيء فيها مثل رفعت حشره او ضرب او نحو ذلك  bug-pit
6  هل اصابك شيء فيها مثل والزعتر تحشر او ضربه عصا...  bug-pit
7  هل اصابك شيء فيها مثل اذا تحشر او ضربت عسى او ...  bug-pit
8  هل اصابك شيء فيها مثل الافعى حشره او ضربه عصا ...  bug-pit
9  هل اصابك شيء فيها مثل لسعات حشره او ضربه عصا ا...  bug-pit

Its look our data is note shuffle lets shuffle them

In [18]:
df = df.sample(frac=1)

In [19]:
df.head()

text     class
51            حسنا اديسون افضل وضع راسك في هذا الجهاز  Sit-down
2   هل اصابك شيء فيها مثل لسعه حشره او ضربه عصا او...   bug-pit
9                                   تشتري هذه النظاره   glasses
23                  هل لديك مرض السكري او اي مرض مزمن     Sugar
15                                    هل تشعر بالصداع  headache

with reset index

In [20]:
df = df.sample(frac=1).reset_index(drop=True)

In [21]:
df.to_csv('train.csv',index=False)

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   text    377 non-null    category
 1   class   377 non-null    category
dtypes: category(2)
memory usage: 6.9 KB


In [187]:
df  = df[['text', 'class']].apply(lambda x: x.astype('category'))

In [188]:
X = df.drop('class', axis=1)
y = df['class']

In [189]:
X.shape, y.shape

((377, 1), (377,))

## EDA

..............................

## Preprocessing

### Convert labeled data to encoded data

In [218]:
from sklearn import preprocessing

In [219]:
le = preprocessing.LabelEncoder()

In [275]:
le.fit(X)

C:\Users\ali\miniconda3\envs\tf\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [276]:
text_encoded = le.transform(X)

C:\Users\ali\miniconda3\envs\tf\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**`because there some problem we most reshape the X value with 2 D`**


In [277]:
text_encoded = text_encoded.reshape(-1, 1)

In [278]:
le.transform(X)

array([ 78, 142, 135,  78,  14,  31,  55,  10,  60,  78,  91, 143, 120,
        78,  63, 148, 109, 142, 142, 148, 136,  32, 148,   1, 148,  60,
       112,  31, 152, 134,  20, 148, 151,  31, 144,  58,  78, 155,  31,
         7, 142,  76,  31,  78,  60, 148,  31,  31,  31, 155,  16,  58,
       148, 103, 128, 148, 116, 148,  78, 142,  65, 126,  91,  60,  60,
        63, 123, 148, 142,  98,  31, 138,  79,  77,  31,  31,  51,  60,
       148,  78,  31,  43,  62,  21, 147,  31,  31, 106, 148,  87,  78,
        78,  15, 155,  37, 147, 148,  60, 142, 121, 142, 148,  30,  52,
        60,  44, 140,  60, 155,  31, 142, 144, 144,  12, 130,  60,   8,
       144, 129,  22, 142,  21, 148,  60, 125,  93,  59, 142,  60, 125,
       125, 104, 102,  27, 142,  34,  31, 154,  78,  31, 148,  60,  75,
       147,  27,  60,  78,   5, 101, 117,  69,  11, 125,  72,  89, 144,
        60,  83,  60,  31,  31,  21,  39, 148,  31,  60, 137, 142,  48,
       125,  35,  66, 148, 148,  46, 142, 119,  78, 147,   6,  2

In [283]:
le.inverse_transform([82])

array(['حسنا اجلس هناك من فضلك ضع راسك في هذه في هذا الجهاز'],
      dtype=object)

In [285]:
le.fit(y)

LabelEncoder()

In [286]:
label_encode = le.transform(y)

In [287]:
le.classes_

array(['Sit-down', 'Sugar', 'bug-pit', 'direction', 'glasses', 'headache',
       'ray'], dtype=object)

In [288]:
y

0      Sit-down
1      headache
2       bug-pit
3      Sit-down
4           ray
         ...   
372    headache
373     glasses
374    Sit-down
375     glasses
376       Sugar
Name: class, Length: 377, dtype: category
Categories (7, object): ['Sit-down', 'Sugar', 'bug-pit', 'direction', 'glasses', 'headache', 'ray']

In [289]:
le.transform(y)

array([0, 5, 2, 0, 6, 4, 3, 6, 3, 0, 0, 5, 2, 0, 3, 1, 2, 5, 5, 1, 2, 4,
       1, 4, 1, 3, 2, 4, 3, 2, 6, 1, 4, 4, 5, 3, 0, 4, 4, 6, 5, 0, 4, 0,
       3, 1, 4, 4, 4, 4, 6, 3, 1, 1, 2, 1, 2, 1, 0, 5, 5, 2, 0, 3, 3, 3,
       2, 1, 5, 6, 4, 5, 0, 0, 4, 4, 6, 3, 1, 0, 4, 4, 0, 6, 1, 4, 4, 2,
       1, 0, 0, 0, 6, 4, 2, 1, 1, 3, 5, 2, 5, 1, 6, 0, 3, 6, 5, 3, 4, 4,
       5, 5, 5, 6, 2, 3, 6, 5, 2, 6, 5, 6, 1, 3, 2, 0, 3, 5, 3, 2, 2, 4,
       3, 6, 5, 6, 4, 0, 0, 4, 1, 3, 0, 1, 6, 3, 0, 0, 3, 2, 0, 6, 2, 0,
       0, 5, 3, 0, 3, 4, 4, 6, 2, 1, 4, 3, 5, 5, 3, 2, 6, 4, 1, 1, 4, 5,
       2, 0, 1, 6, 6, 3, 2, 5, 6, 6, 4, 1, 0, 1, 5, 0, 1, 5, 1, 0, 1, 6,
       2, 4, 3, 6, 4, 6, 2, 5, 6, 5, 6, 5, 0, 3, 1, 2, 2, 0, 3, 6, 6, 2,
       6, 3, 3, 0, 1, 0, 4, 0, 0, 5, 5, 6, 2, 1, 2, 0, 6, 2, 5, 3, 6, 1,
       6, 1, 3, 4, 0, 6, 2, 2, 0, 1, 3, 5, 4, 6, 6, 2, 6, 3, 1, 0, 6, 0,
       1, 4, 5, 0, 3, 2, 4, 3, 4, 0, 6, 0, 0, 3, 5, 3, 4, 3, 0, 2, 5, 3,
       0, 6, 2, 5, 3, 4, 5, 1, 4, 1, 2, 3, 2, 2, 2,

In [291]:
le.inverse_transform([0])

array(['Sit-down'], dtype=object)

AttributeError: 'str' object has no attribute 'shape'

In [143]:
print('Label Encoded',label_encode)

Label Encoded [0 5 2 0 6 4 3 6 3 0 0 5 2 0 3 1 2 5 5 1 2 4 1 4 1 3 2 4 3 2 6 1 4 4 5 3 0
 4 4 6 5 0 4 0 3 1 4 4 4 4 6 3 1 1 2 1 2 1 0 5 5 2 0 3 3 3 2 1 5 6 4 5 0 0
 4 4 6 3 1 0 4 4 0 6 1 4 4 2 1 0 0 0 6 4 2 1 1 3 5 2 5 1 6 0 3 6 5 3 4 4 5
 5 5 6 2 3 6 5 2 6 5 6 1 3 2 0 3 5 3 2 2 4 3 6 5 6 4 0 0 4 1 3 0 1 6 3 0 0
 3 2 0 6 2 0 0 5 3 0 3 4 4 6 2 1 4 3 5 5 3 2 6 4 1 1 4 5 2 0 1 6 6 3 2 5 6
 6 4 1 0 1 5 0 1 5 1 0 1 6 2 4 3 6 4 6 2 5 6 5 6 5 0 3 1 2 2 0 3 6 6 2 6 3
 3 0 1 0 4 0 0 5 5 6 2 1 2 0 6 2 5 3 6 1 6 1 3 4 0 6 2 2 0 1 3 5 4 6 6 2 6
 3 1 0 6 0 1 4 5 0 3 2 4 3 4 0 6 0 0 3 5 3 4 3 0 2 5 3 0 6 2 5 3 4 5 1 4 1
 2 3 2 2 2 3 4 5 6 1 4 2 1 1 2 3 1 1 0 3 5 0 5 3 3 5 4 0 3 1 4 6 6 0 5 5 2
 4 2 5 3 6 2 1 5 6 2 5 3 0 3 3 0 2 1 4 5 5 2 6 2 1 2 2 6 6 4 2 2 5 5 1 6 1
 1 6 5 4 0 4 1]


In [146]:
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])

le.classes_

le.transform([1, 1, 2, 6])

le.inverse_transform([0])

array([1])

**Split the data for train and test**

In [106]:
from sklearn.model_selection import train_test_split# Splitting train : test to 70 : 30 ratio

In [107]:
X_train, X_test, y_train, y_test = train_test_split(text_encoded,label_encode,test_size=0.2)

# the Model

## KNN Algorithm

In [78]:
from sklearn.neighbors import KNeighborsClassifier# Applying k = 3, default Minkowski distance metrics

In [79]:
model = KNeighborsClassifier(n_neighbors=5,algorithm='brute',p=1)# Training the classifier

In [108]:
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='brute', p=1)

In [109]:
model.score(X_test,y_test)

0.881578947368421

## Evalueate the Model `knn` 

**we will use `Mean absolute error` for evaluate the model**

In [111]:
from sklearn.metrics import mean_absolute_error

In [112]:
mean_absolute_error(y_train,model.predict(X_train)) ,mean_absolute_error(y_test,model.predict(X_test))

(0.292358803986711, 0.21052631578947367)

***Oh! its look our model is note good*** berhapse `MAE >2.9 or =3 is not good`\
lets  <b>`Imporve our model`</b>

# Imporve the `KNN Model`

In [284]:
model.predict([[82]])

array([0])

In [306]:
df['text']

0           حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز
1                                        هل تشعر بالصداع
2      هل اصابك شيء فيها مثلثات حشره او ضربتها او نحو...
3           حسنا اجلس هنا من فضلك وضع راسك في هذا الجهاز
4              اذهب الى الاشعه و اعمل صوره اشعه من العين
                             ...                        
372                                        هل تشعر بصداع
373                                    اعتدى هذه النظاره
374      حسنا اجلسوا انا من فضلك وضعه راسك في هذا الجهاز
375                                    ارتدي هذه النظاره
376                         هل لديك مرض السكري او اي مرض
Name: text, Length: 377, dtype: category
Categories (156, object): ['ابتدي هذه النظاره', 'اتعبتني هذه النظاره', 'اجلس هنا من فضلك وضع الماسك في هذا الجهاز', 'اجلس هنا من فضلك وضع راسك في هذا', ..., 'يا اي تيجي هذه العلامه وهذه وهذه وهذه', 'يا اين تتجه هذه العلامه وهذه وهذه وهذه', 'ياشوق حسن اجلس هنا من فضلك وضع السكر في هذه ه..., 'يرتدي هذه النظاره']